// 業種別のアンケート初期テンプレートと、多言語UI文言

// 口コミを自動分類するカテゴリ。分析画面の軸にもなる
export const CATEGORIES = [
  { id: "service", label: "接客", color: "#2563eb" },
  { id: "quality", label: "味・品質", color: "#16a34a" },
  { id: "price", label: "価格", color: "#d97706" },
  { id: "clean", label: "清潔感", color: "#0891b2" },
  { id: "atmosphere", label: "雰囲気", color: "#9333ea" },
  { id: "access", label: "アクセス", color: "#64748b" },
];

export function categoryLabel(id) {
  return CATEGORIES.find((c) => c.id === id)?.label || id;
}

// label: 選択肢の表示 / phrase: 口コミ文に組み込む言い回し
const opt = (cat, label, phrase, en, phraseEn) => ({
  id: Math.random().toString(36).slice(2, 10),
  cat,
  label,
  phrase,
  en,
  phraseEn,
});

export const INDUSTRIES = {
  restaurant: {
    label: "飲食店",
    visitPurpose: ["ランチ", "ディナー", "飲み会", "デート", "家族で", "一人で"],
    options: () => [
      opt("quality", "料理が美味しい", "料理がとても美味しかったです", "Delicious food", "The food was delicious"),
      opt("quality", "盛り付けがきれい", "盛り付けが綺麗で目でも楽しめました", "Beautiful presentation", "The presentation was beautiful"),
      opt("quality", "ドリンクが充実", "ドリンクの種類が豊富で嬉しかったです", "Great drinks", "There was a great selection of drinks"),
      opt("service", "スタッフが親切", "スタッフの方がとても親切でした", "Friendly staff", "The staff were very friendly"),
      opt("service", "提供が早い", "料理の提供がスムーズでした", "Fast service", "The food came out quickly"),
      opt("price", "コスパが良い", "この内容でこの価格はコスパが良いと思います", "Good value", "Great value for the price"),
      opt("clean", "店内が清潔", "店内が清潔で気持ちよく過ごせました", "Clean restaurant", "The restaurant was very clean"),
      opt("atmosphere", "雰囲気が良い", "お店の雰囲気が落ち着いていて居心地が良かったです", "Nice atmosphere", "The atmosphere was cozy"),
      opt("access", "駅から近い", "駅から近くて立ち寄りやすいです", "Close to the station", "It's close to the station"),
    ],
  },
  beauty: {
    label: "美容室・サロン",
    visitPurpose: ["カット", "カラー", "パーマ", "トリートメント", "ネイル", "エステ"],
    options: () => [
      opt("quality", "仕上がりが理想通り", "仕上がりがイメージ通りで大満足です", "Perfect result", "The result was exactly what I wanted"),
      opt("quality", "技術が高い", "技術の高さを感じました", "Skilled stylist", "The stylist was very skilled"),
      opt("service", "カウンセリングが丁寧", "カウンセリングが丁寧で安心してお任せできました", "Careful consultation", "The consultation was thorough"),
      opt("service", "会話が楽しい", "会話も楽しくあっという間の時間でした", "Pleasant conversation", "The conversation was enjoyable"),
      opt("price", "価格が明確", "料金が明確で安心でした", "Clear pricing", "The pricing was clear"),
      opt("clean", "店内が清潔", "店内が清潔で気持ちよかったです", "Clean salon", "The salon was clean"),
      opt("atmosphere", "リラックスできた", "リラックスして過ごせました", "Relaxing", "It was very relaxing"),
      opt("access", "予約が取りやすい", "予約が取りやすくて助かります", "Easy booking", "Booking was easy"),
    ],
  },
  clinic: {
    label: "歯科・クリニック",
    visitPurpose: ["初診", "定期検診", "治療", "クリーニング", "相談"],
    options: () => [
      opt("quality", "説明が分かりやすい", "治療内容の説明が分かりやすかったです", "Clear explanations", "The explanations were easy to understand"),
      opt("quality", "痛みが少ない", "痛みへの配慮があり安心できました", "Little pain", "They were careful to minimize pain"),
      opt("service", "受付が丁寧", "受付の方の対応が丁寧でした", "Polite reception", "The reception staff were polite"),
      opt("service", "待ち時間が短い", "待ち時間が短くスムーズでした", "Short wait", "The wait time was short"),
      opt("price", "費用の説明が明確", "費用について事前にきちんと説明してもらえました", "Clear costs", "Costs were explained in advance"),
      opt("clean", "院内が清潔", "院内が清潔で安心感がありました", "Clean clinic", "The clinic was very clean"),
      opt("atmosphere", "落ち着いた雰囲気", "院内が落ち着いた雰囲気でした", "Calm atmosphere", "The atmosphere was calm"),
      opt("access", "通いやすい", "立地が良く通いやすいです", "Convenient location", "The location is convenient"),
    ],
  },
  hotel: {
    label: "ホテル・宿泊",
    visitPurpose: ["観光", "出張", "家族旅行", "記念日", "一人旅"],
    options: () => [
      opt("quality", "部屋が快適", "お部屋が快適でぐっすり眠れました", "Comfortable room", "The room was very comfortable"),
      opt("quality", "朝食が美味しい", "朝食がとても美味しかったです", "Great breakfast", "Breakfast was excellent"),
      opt("service", "フロントが親切", "フロントの方の対応がとても親切でした", "Helpful front desk", "The front desk staff were very helpful"),
      opt("price", "価格以上の満足感", "価格以上の満足感がありました", "Great value", "It was worth more than the price"),
      opt("clean", "清掃が行き届いている", "清掃が行き届いていて気持ちよかったです", "Very clean", "Everything was spotless"),
      opt("atmosphere", "眺めが良い", "部屋からの眺めが素晴らしかったです", "Great view", "The view was amazing"),
      opt("access", "観光に便利", "観光の拠点としてとても便利な立地でした", "Convenient for sightseeing", "The location is great for sightseeing"),
    ],
  },
  shisha: {
    label: "シーシャ・バー",
    visitPurpose: ["一人で", "友人と", "デート", "作業", "二軒目"],
    options: () => [
      opt("quality", "フレーバーが美味しい", "フレーバーがとても美味しかったです", "Tasty flavors", "The flavors were delicious"),
      opt("quality", "煙が濃くて長持ち", "煙がしっかり出て最後まで楽しめました", "Rich, long-lasting smoke", "The smoke was rich and lasted long"),
      opt("service", "好みを聞いて調合", "好みを丁寧に聞いてミックスを作ってもらえました", "Custom mix", "They made a mix tailored to my taste"),
      opt("service", "炭替えがこまめ", "炭替えがこまめで快適でした", "Attentive coal service", "Coal changes were attentive"),
      opt("price", "価格が手頃", "価格も手頃で通いやすいです", "Reasonable price", "Prices are reasonable"),
      opt("clean", "店内が清潔", "店内が清潔で居心地が良かったです", "Clean", "The place was clean"),
      opt("atmosphere", "ゆっくりできる", "ソファが快適でゆっくり過ごせました", "Relaxing space", "It was a great place to relax"),
    ],
  },
  other: {
    label: "その他",
    visitPurpose: ["初めて", "リピート", "紹介"],
    options: () => [
      opt("quality", "品質が高い", "サービスの質が高いと感じました", "High quality", "The quality was high"),
      opt("service", "対応が丁寧", "対応がとても丁寧でした", "Polite service", "The service was polite"),
      opt("price", "価格に納得", "価格にも納得です", "Fair price", "The price was fair"),
      opt("clean", "清潔感がある", "清潔感がありました", "Clean", "It was clean"),
      opt("atmosphere", "雰囲気が良い", "雰囲気が良かったです", "Nice atmosphere", "The atmosphere was nice"),
    ],
  },
};

export function newStore(industry = "restaurant") {
  const ind = INDUSTRIES[industry] || INDUSTRIES.other;
  return {
    id: Math.random().toString(36).slice(2, 10),
    name: "",
    industry,
    googleReviewUrl: "",
    options: ind.options(),
    visitPurpose: [...ind.visitPurpose],
    ngWords: [],
    tone: "friendly", // friendly | polite | casual
    coupon: { enabled: false, mode: "coupon", title: "", body: "", code: "", winRate: 30 },
    languages: ["ja", "en", "zh", "ko"],
    googleStats: { rating: "", count: "" },
    createdAt: new Date().toISOString(),
  };
}

export const LANGS = {
  ja: "日本語",
  en: "English",
  zh: "中文",
  ko: "한국어",
};

// 顧客アンケート画面の文言
export const T = {
  ja: {
    hello: "ご来店ありがとうございます",
    lead: "30秒で終わるアンケートにご協力ください",
    q1: "今回のご満足度は？",
    q2: "ご利用シーン",
    q3: "良かった点を選んでください（複数可）",
    q4: "ひとことあれば（任意）",
    placeholder: "例：また来たいです",
    next: "次へ",
    back: "戻る",
    generating: "口コミ文を作成中…",
    draftTitle: "口コミ文の下書きができました",
    draftNote: "ご自身の言葉に自由に書き換えてください。内容に問題なければコピーしてGoogleに投稿できます。",
    copyAndPost: "コピーしてGoogleで投稿する",
    copied: "コピーしました！Googleの投稿画面に貼り付けてください",
    skipGoogle: "投稿せずに終了する",
    lowTitle: "ご期待に沿えず申し訳ありません",
    lowLead: "改善のため、お気づきの点をお店に直接お伝えいただけますか？",
    sendToStore: "お店に送信する",
    alsoGoogle: "Googleにも口コミを書く",
    thanks: "ご協力ありがとうございました！",
    couponTitle: "ご回答特典",
    lotteryWin: "おめでとうございます！当たりです🎉",
    lotteryLose: "残念、はずれです。またのご来店をお待ちしています",
    showStaff: "この画面をスタッフにご提示ください",
    ngWarn: "使用できない言葉が含まれています",
    regenerate: "別の文章を作る",
    rateFirst: "満足度を選んでください",
  },
  en: {
    hello: "Thank you for visiting!",
    lead: "Please take our 30-second survey",
    q1: "How satisfied were you?",
    q2: "Occasion",
    q3: "What did you like? (multiple choice)",
    q4: "Any comments? (optional)",
    placeholder: "e.g. I'd love to come back",
    next: "Next",
    back: "Back",
    generating: "Writing your review draft…",
    draftTitle: "Your review draft is ready",
    draftNote: "Feel free to edit it in your own words. Then copy it and post on Google.",
    copyAndPost: "Copy & post on Google",
    copied: "Copied! Paste it into the Google review form",
    skipGoogle: "Finish without posting",
    lowTitle: "We're sorry we didn't meet your expectations",
    lowLead: "Could you tell the store directly what we can improve?",
    sendToStore: "Send to the store",
    alsoGoogle: "Also write a Google review",
    thanks: "Thank you!",
    couponTitle: "Your reward",
    lotteryWin: "Congratulations, you won! 🎉",
    lotteryLose: "Not this time. We hope to see you again!",
    showStaff: "Please show this screen to our staff",
    ngWarn: "Contains words that cannot be used",
    regenerate: "Write another version",
    rateFirst: "Please choose a rating",
  },
  zh: {
    hello: "感谢您的光临",
    lead: "请花30秒填写问卷",
    q1: "您的满意度如何？",
    q2: "用餐/使用场景",
    q3: "请选择满意的地方（可多选）",
    q4: "其他意见（可选）",
    placeholder: "例：还想再来",
    next: "下一步",
    back: "返回",
    generating: "正在生成评价草稿…",
    draftTitle: "评价草稿已生成",
    draftNote: "您可以自由修改。确认后复制并发布到Google。",
    copyAndPost: "复制并在Google发布",
    copied: "已复制！请粘贴到Google评价页面",
    skipGoogle: "不发布，直接结束",
    lowTitle: "很抱歉没能让您满意",
    lowLead: "能否直接告诉店铺需要改进的地方？",
    sendToStore: "发送给店铺",
    alsoGoogle: "也在Google写评价",
    thanks: "感谢您的配合！",
    couponTitle: "回答特典",
    lotteryWin: "恭喜中奖！🎉",
    lotteryLose: "很遗憾没有中奖，期待您再次光临",
    showStaff: "请向店员出示此画面",
    ngWarn: "包含不可使用的词语",
    regenerate: "重新生成",
    rateFirst: "请选择满意度",
  },
  ko: {
    hello: "방문해 주셔서 감사합니다",
    lead: "30초 설문에 협조 부탁드립니다",
    q1: "만족도는 어떠셨나요?",
    q2: "이용 목적",
    q3: "좋았던 점을 선택해 주세요 (복수 선택)",
    q4: "한마디 (선택)",
    placeholder: "예: 또 오고 싶어요",
    next: "다음",
    back: "뒤로",
    generating: "리뷰 초안 작성 중…",
    draftTitle: "리뷰 초안이 완성되었습니다",
    draftNote: "자유롭게 수정해 주세요. 확인 후 복사하여 Google에 게시할 수 있습니다.",
    copyAndPost: "복사하고 Google에 게시",
    copied: "복사했습니다! Google 리뷰 화면에 붙여넣어 주세요",
    skipGoogle: "게시하지 않고 종료",
    lowTitle: "기대에 미치지 못해 죄송합니다",
    lowLead: "개선을 위해 매장에 직접 의견을 보내주시겠어요?",
    sendToStore: "매장에 보내기",
    alsoGoogle: "Google에도 리뷰 쓰기",
    thanks: "협조해 주셔서 감사합니다!",
    couponTitle: "응답 특전",
    lotteryWin: "축하합니다! 당첨입니다 🎉",
    lotteryLose: "아쉽게도 꽝입니다. 또 방문해 주세요",
    showStaff: "이 화면을 직원에게 보여주세요",
    ngWarn: "사용할 수 없는 단어가 포함되어 있습니다",
    regenerate: "다른 문장 만들기",
    rateFirst: "만족도를 선택해 주세요",
  },
};
